$INCLUDE_FILE


(* GLOBALE TYPEN *)



(* PROJEKT TYPEN *)



(* GLOBALE PROTOTYPEN *)

FUNCTION_BLOCK INT_TO_DINT_EN
    VAR_INPUT                                              
      EN :BOOL;
      IN :INT;
    END_VAR
    VAR_OUTPUT
      ENO :BOOL;
      OUT :DINT;
    END_VAR
  END_FUNCTION_BLOCK



(* PROJEKT PROTOTYPEN *)



(* EXTERNE POEs *)



$END_INCLUDE_FILE
